FROM apache/airflow:2.10.0

USER airflow

RUN pip install --no-cache-dir \
    beautifulsoup4 \
    requests \
    pandas \
    pyarrow \
    minio \
    psycopg2-binary \
    langdetect \
    kafka-python \
    lxml